package varasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import varasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.30 23:15:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuotteetTest {


  // Generated by ComTest BEGIN
  /** testMuutaVarastoarvoa147 */
  @Test
  public void testMuutaVarastoarvoa147() {    // Tuotteet: 147
    Tuotteet tuotteet = new Tuotteet(); 
    Tuote tuote = new Tuote(); 
    assertEquals("From: Tuotteet line: 150", 0, tuote.getVarastoarvo()); 
    tuotteet.muutaVarastoarvoa(tuote, -2); 
    assertEquals("From: Tuotteet line: 152", -2, tuote.getVarastoarvo()); 
    tuotteet.muutaVarastoarvoa(tuote, 2); 
    assertEquals("From: Tuotteet line: 154", 0, tuote.getVarastoarvo()); 
    try {
    tuotteet.lisaa(tuote); 
    } catch(Exception e) {
    System.out.println("ei toimi"); 
    }
    assertEquals("From: Tuotteet line: 160", 1, tuotteet.getLukumaara()); 
    assertEquals("From: Tuotteet line: 161", tuote, tuotteet.getAlkiot(0)); 
    Tuote tuote2 = new Tuote(); 
    Tuote tuote3 = new Tuote(); 
    Tuote tuote4 = new Tuote(); 
    Tuote tuote5 = new Tuote(); 
    try {
    tuotteet.lisaa(tuote2); 
    tuotteet.lisaa(tuote3); 
    tuotteet.lisaa(tuote4); 
    tuotteet.lisaa(tuote5); 
    } catch(Exception e) {
    System.out.println("ei toimi"); 
    }
    assertEquals("From: Tuotteet line: 174", 5, tuotteet.getLukumaara()); 
  } // Generated by ComTest END
}