package varasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import varasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.01 12:57:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuoteTest {



  // Generated by ComTest BEGIN
  /** testAseta130 */
  @Test
  public void testAseta130() {    // Tuote: 130
    Tuote sanky = new Tuote(); 
    Tuote sanky2 = new Tuote(); 
    Tuote sanky3 = new Tuote(); 
    sanky.aseta(); 
    sanky2.aseta(); 
    sanky3.aseta(); 
    assertEquals("From: Tuote line: 137", sanky2.getTuotenumero() + 1, sanky3.getTuotenumero()); 
    assertEquals("From: Tuote line: 138", sanky.getTuotenumero() + 1, sanky2.getTuotenumero()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testOikeellisuusTarkistus173 */
  @Test
  public void testOikeellisuusTarkistus173() {    // Tuote: 173
    Tuote sohva = new Tuote(); 
    sohva.oikeellisuusTarkistus("Patja", "Aktiivinen", 22, 50, 2); 
    assertEquals("From: Tuote line: 176", "Patja", sohva.getNimi()); 
    assertEquals("From: Tuote line: 177", 22, sohva.getVarastoarvo()); 
    assertEquals("From: Tuote line: 178", 50, sohva.getVarastokapasiteetti()); 
    assertEquals("From: Tuote line: 179", 2, sohva.getKollit()); 
    assertEquals("From: Tuote line: 180", "Aktiivinen", sohva.getStatus()); 
    sohva.oikeellisuusTarkistus("", "Aktiivinen", 22, 50, 2); 
    assertEquals("From: Tuote line: 182", "Patja", sohva.getNimi()); 
    assertEquals("From: Tuote line: 183", 22, sohva.getVarastoarvo()); 
    assertEquals("From: Tuote line: 184", 50, sohva.getVarastokapasiteetti()); 
    assertEquals("From: Tuote line: 185", 2, sohva.getKollit()); 
    assertEquals("From: Tuote line: 186", "Aktiivinen", sohva.getStatus()); 
    sohva.oikeellisuusTarkistus("SOHVA", "Poistunut", 232, 560, 24); 
    assertEquals("From: Tuote line: 188", "SOHVA", sohva.getNimi()); 
    assertEquals("From: Tuote line: 189", 232, sohva.getVarastoarvo()); 
    assertEquals("From: Tuote line: 190", 560, sohva.getVarastokapasiteetti()); 
    assertEquals("From: Tuote line: 191", 24, sohva.getKollit()); 
    assertEquals("From: Tuote line: 192", "Poistunut", sohva.getStatus()); 
  } // Generated by ComTest END
}