package varasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import varasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.21 14:37:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VarastonkorjauksetTest {



  // Generated by ComTest BEGIN
  /** testLisaa53 */
  @Test
  public void testLisaa53() {    // Varastonkorjaukset: 53
    Varastonkorjaukset varastonkorjaukset = new Varastonkorjaukset(); 
    assertEquals("From: Varastonkorjaukset line: 55", 0, varastonkorjaukset.getLukumaara()); 
    Varastonkorjaus korjaus = new Varastonkorjaus(); 
    Varastonkorjaus korjaus2 = new Varastonkorjaus(); 
    korjaus.alusta(1001, 2, "Varastonkorjaus"); 
    korjaus2.alusta(1000, 3, "Varastonkorjaus"); 
    varastonkorjaukset.lisaa(korjaus); 
    varastonkorjaukset.lisaa(korjaus2); 
    assertEquals("From: Varastonkorjaukset line: 62", 2, varastonkorjaukset.getLukumaara()); 
    assertEquals("From: Varastonkorjaukset line: 63", korjaus, varastonkorjaukset.getAlkiot(0)); 
    assertEquals("From: Varastonkorjaukset line: 64", korjaus2, varastonkorjaukset.getAlkiot(1)); 
  } // Generated by ComTest END
}