package varasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import varasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.21 14:51:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VarastoTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa114 
   * @throws TaynnaException when error
   */
  @Test
  public void testLisaa114() throws TaynnaException {    // Varasto: 114
    Varasto varasto = new Varasto(); 
    Tuote tyyny = new Tuote(); 
    Tuote tyyny2 = new Tuote(); 
    Tuote tyyny3 = new Tuote(); 
    tyyny.aseta(); 
    tyyny2.aseta(); 
    tyyny3.aseta(); 
    assertEquals("From: Varasto line: 123", 0, varasto.getTuotteita()); 
    varasto.lisaa(tyyny); assertEquals("From: Varasto line: 124", 1, varasto.getTuotteita()); 
    varasto.lisaa(tyyny2); assertEquals("From: Varasto line: 125", 2, varasto.getTuotteita()); 
    varasto.lisaa(tyyny3); assertEquals("From: Varasto line: 126", 3, varasto.getTuotteita()); 
    assertEquals("From: Varasto line: 127", tyyny, varasto.annaTuote(0)); 
    assertEquals("From: Varasto line: 128", tyyny2, varasto.annaTuote(1)); 
    assertEquals("From: Varasto line: 129", tyyny3, varasto.annaTuote(2)); 
    assertEquals("From: Varasto line: 130", null, varasto.annaTuote(3)); 
  } // Generated by ComTest END
}