package varasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import varasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.30 23:29:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VarastoTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa111 
   * @throws TaynnaException when error
   */
  @Test
  public void testLisaa111() throws TaynnaException {    // Varasto: 111
    Varasto varasto = new Varasto(); 
    Tuote tyyny = new Tuote(); 
    Tuote tyyny2 = new Tuote(); 
    Tuote tyyny3 = new Tuote(); 
    tyyny.aseta("Tyyny",2,2,"Aktiivinen"); 
    tyyny2.aseta("Tyyny",2,2,"Aktiivinen"); 
    tyyny3.aseta("Tyyny",2,2,"Aktiiinen"); 
    assertEquals("From: Varasto line: 120", 0, varasto.getTuotteita()); 
    varasto.lisaa(tyyny); assertEquals("From: Varasto line: 121", 1, varasto.getTuotteita()); 
    varasto.lisaa(tyyny2); assertEquals("From: Varasto line: 122", 2, varasto.getTuotteita()); 
    assertEquals("From: Varasto line: 123", tyyny, varasto.annaTuote(0)); 
    assertEquals("From: Varasto line: 124", tyyny2, varasto.annaTuote(1)); 
    assertEquals("From: Varasto line: 125", null, varasto.annaTuote(2)); 
    assertEquals("From: Varasto line: 126", null, varasto.annaTuote(3)); 
    Varastonkorjaus korjaus = new Varastonkorjaus(); 
    korjaus.alusta(1000, "Varastonkorjaus", 3); 
    assertEquals("From: Varasto line: 129", 0, varasto.getVarastonkorjauksia()); 
    varasto.lisaaKorjaus(korjaus); 
    assertEquals("From: Varasto line: 131", 0, varasto.getVarastonkorjauksia()); 
    Varastonkorjaus korjaus2 = new Varastonkorjaus(); 
    korjaus2.alusta(1, "Varastonkorjaus", 3); 
    varasto.lisaaKorjaus(korjaus2); 
    assertEquals("From: Varasto line: 135", 1, varasto.getVarastonkorjauksia()); 
  } // Generated by ComTest END
}