package varasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import varasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.29 12:57:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VarastonkorjausTest {



  // Generated by ComTest BEGIN
  /** testAlusta105 */
  @Test
  public void testAlusta105() {    // Varastonkorjaus: 105
    Varastonkorjaus korjaus = new Varastonkorjaus(); 
    Varastonkorjaus korjaus2 = new Varastonkorjaus(); 
    korjaus.alusta(1, 2, "Varastonkorjaus"); 
    assertEquals("From: Varastonkorjaus line: 109", 1, korjaus.getTuotenumero()); 
    assertEquals("From: Varastonkorjaus line: 110", "29.02.2020", korjaus.getPaiva()); 
    assertEquals("From: Varastonkorjaus line: 111", 2, korjaus.getMuutos()); 
    assertEquals("From: Varastonkorjaus line: 112", "Varastonkorjaus", korjaus.getTapahtuma()); 
    assertEquals("From: Varastonkorjaus line: 113", 1, korjaus.getVkid()); 
    korjaus2.alusta(1, 2, "Varastonkorjaus"); 
    assertEquals("From: Varastonkorjaus line: 115", 1, korjaus2.getTuotenumero()); 
    assertEquals("From: Varastonkorjaus line: 116", "29.02.2020", korjaus2.getPaiva()); 
    assertEquals("From: Varastonkorjaus line: 117", 2, korjaus2.getMuutos()); 
    assertEquals("From: Varastonkorjaus line: 118", "Varastonkorjaus", korjaus2.getTapahtuma()); 
    assertEquals("From: Varastonkorjaus line: 119", 2, korjaus2.getVkid()); 
  } // Generated by ComTest END
}