package varasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import varasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.30 23:32:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VarastonkorjauksetTest {


  // Generated by ComTest BEGIN
  /** testLisaa57 */
  @Test
  public void testLisaa57() {    // Varastonkorjaukset: 57
    Varastonkorjaukset varastonkorjaukset = new Varastonkorjaukset(); 
    assertEquals("From: Varastonkorjaukset line: 59", 0, varastonkorjaukset.getLukumaara()); 
    Varastonkorjaus korjaus = new Varastonkorjaus(); 
    Varastonkorjaus korjaus2 = new Varastonkorjaus(); 
    korjaus.alusta(1001, "Varastonkorjaus",2); 
    korjaus2.alusta(1000,  "Varastonkorjaus",2); 
    varastonkorjaukset.lisaa(korjaus); 
    varastonkorjaukset.lisaa(korjaus2); 
    assertEquals("From: Varastonkorjaukset line: 66", 2, varastonkorjaukset.getLukumaara()); 
    assertEquals("From: Varastonkorjaukset line: 67", korjaus, varastonkorjaukset.getAlkiot(0)); 
    assertEquals("From: Varastonkorjaukset line: 68", korjaus2, varastonkorjaukset.getAlkiot(1)); 
  } // Generated by ComTest END
}