package varasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import varasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.30 23:30:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class VarastonkorjausTest {


  // Generated by ComTest BEGIN
  /** testAlusta103 */
  @Test
  public void testAlusta103() {    // Varastonkorjaus: 103
    Varastonkorjaus korjaus = new Varastonkorjaus(); 
    Varastonkorjaus korjaus2 = new Varastonkorjaus(); 
    korjaus.alusta(1,"Varastonkorjaus",2); 
    assertEquals("From: Varastonkorjaus line: 107", 1, korjaus.getTuotenumero()); 
    assertEquals("From: Varastonkorjaus line: 108", 2, korjaus.getMuutos()); 
    assertEquals("From: Varastonkorjaus line: 109", "Varastonkorjaus", korjaus.getTapahtuma()); 
    assertEquals("From: Varastonkorjaus line: 110", 1, korjaus.getVkid()); 
    korjaus2.alusta(1,"Varastonkorjaus",2); 
    assertEquals("From: Varastonkorjaus line: 112", 1, korjaus2.getTuotenumero()); 
    assertEquals("From: Varastonkorjaus line: 113", 2, korjaus2.getMuutos()); 
    assertEquals("From: Varastonkorjaus line: 114", "Varastonkorjaus", korjaus2.getTapahtuma()); 
    assertEquals("From: Varastonkorjaus line: 115", 2, korjaus2.getVkid()); 
  } // Generated by ComTest END
}